var tasks = [
    "Give Simba a pat and take a photo with him",
    "Find someone who wears glasses",
    "Find the shortest person in the office",
    "Water a plant but only with 1 drop of water", 
    "Eat a sweet snack with an office peep", 
    "Find someone who is wearing something purple",
    "Take a photo drinking out of your WEBTOON hydroflask with someone who also has a WEBTOON hydroflask", 
    "Find the tallest person in the office", 
    "Find a turtle with an office peep",
    "Take a photo with someone wearing stripes", 
    "Take a quick walk with someone outside of your department", 
    "Find someone who got Starbucks today and show us what their drink order was",
    "FREE", 
    "Write a nice note on a post-it and give it to someone at the office",
    "Take a photo of one of our air purifiers", 
    "Eat a spicy snack with an office peep", 
    "Eat lunch with a peer or team member",
    "Figure out today’s Slack wordle with a partner", 
    "Find someone who drives a red car",
    "Check out a food truck or the farmers market at the office building", 
    "Give a high-five to someone who is born in May-June", 
    "Find an inanimate cute item or plush to take a photo with", 
    "Take a photo with your desk buddy (someone who sits next to you!)", 
    "Snap a photo of what today’s catered lunch is", 
    "Take a “candid” photo of yourself or a peer reading a manga, WP or WE comic/book!",
]

export {tasks}